#!/usr/bin/fish

# Usage: lcat <path>
# Behaves like `ls` if `path` is a directory, and `bat`/`cat` if
# `path` is a file.

function lcat
    set path $argv[1]
    if test -d $path
        ls -lvF $path
    else
        if type -q batcat
            batcat $path
        else
            cat $path
        end
    end
end

lcat $argv[1]